version: '2'
services:
  lexml-parser:
    image: lexmlbr/parser-projeto-lei-ws:{{gittag}}
    mem_limit: 1073741824
    environment:
       - LEXML_PARSER_APP_ENV=producao
       - PARSER_CLUSTER_SIZE=2
    volumes: 
      - /mnt/containers-volumes/producao/lexml-parser/logs1:/lexml-parser-pl/logs:rw
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-app=true
      prom.port: 8080
      prom.path: /lexml-parser/sfstatus/metrics
      prom.target: service
      lb.java.prd.somente_interno.porta: '8080'
      lb.java.prd.somente_interno.healthcheck: /lexml-parser/sfstatus/ping
      lb.java.prd.somente_interno.sticksession: true
