version: '2'
services:
  parser1:
    image: lexmlbr/parser-projeto-lei-ws:{{gittag}}
    volumes:
      - /mnt/containers-volumes/producao/lexml-parser/parser:/areastorage/parser
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-app=true
      prom.port: 8080
      prom.path: /lexml-parser/sfstatus/metrics
      prom.target: service
  parser2:
    image: lexmlbr/parser-projeto-lei-ws:{{gittag}}
    volumes:
      - /mnt/containers-volumes/producao/lexml-parser/parser:/areastorage/parser
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-app=true
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=lexml-parser/parser1
      prom.port: 8080
      prom.path: /lexml-parser/sfstatus/metrics
      prom.target: service
