version: '2'
services:
  parser1:
    image: lexmlbr/parser-projeto-lei-ws:{{gittag}}
    volumes:
      - /mnt/containers-volumes/desenvolvimento/lexml-parser-hml/parser:/areastorage/parser
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-backend=true
  parser2:
    image: lexmlbr/parser-projeto-lei-ws:{{gittag}}
    volumes:
      - /mnt/containers-volumes/desenvolvimento/lexml-parser-hml/parser:/areastorage/parser
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-backend=true
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=lexml-parser-hml/parser1
