version: '2'
services:
  lexml-parser:
    scale: 2
    start_on_create: true
    health_check:
          port: 8080
          request_line: GET /lexml-parser/parse/static/simulador/simulador.html HTTP/1.0
          initializing_timeout: 120000
          reinitializing_timeout: 120000
          interval: 10000
          response_timeout: 10000
          healthy_threshold: 2
          unhealthy_threshold: 3
          strategy: recreate
