version: '2'
services:
  parser1:
    image: lexmlbr/parser-projeto-lei-ws
    volumes:
      - /tmp/parser:/areastorage/parser
  parser2:
    image: lexmlbr/parser-projeto-lei-ws
    volumes:
      - /tmp/parser:/areastorage/parser
  nginx:
    build: ./nginx
    depends_on:
      - parser1
    ports:
      - "443:443"
