version: '2'
services:
  parser1:
    image: lexmlbr/parser-projeto-lei-ws
    volumes:
      - /mnt/container-volumes/desenvolvimento/lexml-parser-dsv/parser:/areastorage/parser
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: role-backend=true
