version: '2'
services:
  parser1:
    scale: 1
    start_on_create: true
    health_check:
          port: 8080
          request_line: GET /lexml-parser/parse/static/simulador/simulador.html HTTP/1.0
          initializing_timeout: 20000
          reinitializing_timeout: 20000
          interval: 10000
          response_timeout: 5000
          healthy_threshold: 2
          unhealthy_threshold: 3
          strategy: none
  parser2:
    scale: 1
    start_on_create: true
    health_check:
          port: 8080
          request_line: GET /lexml-parser/parse/static/simulador/simulador.html HTTP/1.0
          initializing_timeout: 20000
          reinitializing_timeout: 20000
          interval: 10000
          response_timeout: 5000
          healthy_threshold: 2
          unhealthy_threshold: 3
          strategy: none
