version: '2'
services:
  parser1:
    scale: 1
    start_on_create: true
    health_check:
          port: 8080
          request_line: GET /lexml-parser/sfstatus/ping HTTP/1.0
          initializing_timeout: 120000
          reinitializing_timeout: 120000
          interval: 10000
          response_timeout: 10000
          healthy_threshold: 2
          unhealthy_threshold: 3
          strategy: recreate
    volumes:
      lexml-parser-dsv-log-1:/var/log/lexml-parser-dsv-log
    labels:
      io.rancher.sidekicks: filebeat1
  filebeat1:
    scale: 1
    start_on_create: true
    volumes:
      lexml-parser-dsv-log-1:/var/log/lexml-parser-dsv-log
  parser2:
    scale: 1
    start_on_create: true
    health_check:
          port: 8080
          request_line: GET /lexml-parser/sfstatus/ping HTTP/1.0
          initializing_timeout: 120000
          reinitializing_timeout: 120000
          interval: 10000
          response_timeout: 10000
          healthy_threshold: 2
          unhealthy_threshold: 3
          strategy: recreate
